name: CI Workflow Ignix-UI

on:
  push:
    branches:
      - "**"  # Allow CI on all branches
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_scope:
    runs-on: ubuntu-latest
    outputs:
      scope: ${{ steps.scope-check.outputs.scope }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run scope check
        id: scope-check
        run: |
          bash scripts/check-scope.sh
          echo "scope=${scope}" >> $GITHUB_OUTPUT

  build:
    name: '@mindfiredigital/ignix-ui'
    needs: check_scope
    if: needs.check_scope.outputs.scope == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run lint
        run: pnpm run lint

      - name: Log scope status
        run: echo "üîç CI job executed because valid scope was found in commit message"

      - name: Debug scope output
        run: echo "Scope output is:${{ needs.check_scope.outputs.scope }}"

